### ISSUE TITLE
How to programmatically deselect layers?

### ISSUE THREAD

**Issue by Nexus6** [davicustodio/Leaflet.StyledLayerControl#1]
From the docs and perusing the source, there doesn't seem to be a way to do this.  Because of the way my app works, I want overlays in some of the groups to be exclusive -- essentially want radio-button functionality rather than checkboxes.  I thought I'd just do that myself, catching the map's layeradd event and from that deselecting (equivalent to unchecking a layer checkbox) all layers but that layer pertaining to the event.  But there doesn't seem to be a way to do this, via the API I can only remove layers entirely.  Any suggestions for how to approach this?  Workaround?  If not, consider this a feature request.  :)

**Comment by davicustodio** [comment]
As the plugin was based on the original class of Leaflet: L.control.layers, understand that this is not possible. The L.control.layers believes that the layers are divided into two groups: the basemaps and overlays, and the basemaps are unique (radiobuttons) and overlays not (checkbox). Another problem related to L.control.layers class is dealing as an active layer that has been added to the map and inactive one that was excluded map.
When I started writing the StyledLayerControl inheriting from L.control.layers realized that if I were to write L.control.layers do differently in this regard.
I understand that to be able to implement it would be best to get a zero plugin, without inheriting any class, and implement a new concept in relation to the administration of Layers.
Even so, I accept suggestions for some way around this in StyledLayerControl.

Thanks for the input.

**Comment by davicustodio** [comment]
@Nexus6 Today I had some extra time and decided to further verify this Issue. I found that the solution was easy.
recently implemented that commits 9aa993ad5ecbb447ec90359ce6acc6e23defc182
