### ISSUE TITLE
Allow to inspect added groups and layers

### ISSUE THREAD

**Issue by neothemachine** [davicustodio/Leaflet.StyledLayerControl#18]
It would be nice if it was possible to query the layer control to get some information about the groups and its layers. Several independent parts of my app add and remove layers to a fixed group, and I'd like to implement that whoever removes the last layer in the group also has to delete the group itself. But since I can't check if the group still has layers this is not easily possible.

**Comment by davicustodio** [comment]
@neothemachine try inspect control._groupList and control._layers
