### ISSUE TITLE
how to set the height of expanded control to 100% of map frame?

### ISSUE THREAD

**Issue by vkrapotkin** [davicustodio/Leaflet.StyledLayerControl#19]

**Comment by davicustodio** [comment]
@vkrapotkin there was a problem with the automatic adaptation of the Styled Layer Control with the size of the main window. Just fix it in the commit af2f80e48c66ecc30d44219911a9a0bb868a7909
Hopefully solve your problem

**Comment by vkrapotkin** [comment]
sorry but I didn't understand how to do it
we only have the "container_maxHeight" option, although I need something like "container_height"
I want to place popup at 100% height aligned to right border and to divide it into 2 equal groups

**Comment by davicustodio** [comment]
@vkrapotkin I did some tests and climb the branch test_group_height, you can try here d79b6317effdce26ef9080f0f73495604b490667.
I realized that enable a height for each group disables the ability to check / uncheck the groups.
Still do not know how to resolve this situation, but maybe if you have any ideas to share with us.

![image](https://cloud.githubusercontent.com/assets/1775066/13329866/132fb416-dbd5-11e5-936d-efc03afa58ff.png)

**Comment by davicustodio** [comment]
@vkrapotkin best you see here 1044033973713986774e0f6849ca8016b4c709a9
