### ISSUE TITLE
Set layers as visible by default

### ISSUE THREAD

**Issue by mibalas** [davicustodio/Leaflet.StyledLayerControl#20]
Hi, how can I set layers as visible by default?
I tried to put "visible: true" by doenst work.

**Comment by davicustodio** [comment]
@mibalas i include the visible attribute to the StyledControl options in e0c8133ed90040ceed80d54aeb1e872c6572f990.
Only need to merge the master branch.

Thanks

**Comment by mibalas** [comment]
Great! 

thank you!
