### ISSUE TITLE
styledLayerControl turn visibility on by default without needing an on mouse hover event 

### ISSUE THREAD

**Issue by vlasvlasvlas** [davicustodio/Leaflet.StyledLayerControl#21]
Hi!

How do iturn styledLayerControl by default visibility on without needing an on mouse hover event when document is ready?

Thanks!

**Comment by davicustodio** [comment]
@vlasvlasvlas  in the options, set collapsed to false, like this : 

var options = {
				container_width 	: "300px",
				group_maxHeight     : "80px",
				//container_maxHeight : "350px", 
				exclusive       	: false,
				collapsed : false, 
				position: 'topright'
			};
		
var control = L.Control.styledLayerControl(baseMaps, overlays, options);
map.addControl(control);

**Comment by vlasvlasvlas** [comment]
Thanks alot!
