### ISSUE TITLE
Select/Deselect all overlays in group?

### ISSUE THREAD

**Issue by TORParse** [davicustodio/Leaflet.StyledLayerControl#3]
Is there a way to add functionality to select/deselect all of the layers in a particular layer group? I have a few layer groups that have quite a few layers in them, and I'd like to quickly be able to check/uncheck them all. Thanks!

**Comment by davicustodio** [comment]
@TORParse the implementation aea3442d236addb018d8a353ec2eb7f730ca4436 can select/unselect layers in a group.

**Comment by mibalas** [comment]
Hi, how can I add this function to a checkbox?

example: on click: show all layers of group

thanks

**Comment by davicustodio** [comment]
@mibalas  The plugin does not provide visually a checkbox to select all layers, you will need to implement it in the plugin design, and invoke selectGroup  aea3442
