### ISSUE TITLE
Added layers come invisible

### ISSUE THREAD

**Issue by clluiz** [davicustodio/Leaflet.StyledLayerControl#6]
The layers added on the map come invisible, it's possible to set de default to visible?

**Comment by davicustodio** [comment]
I do not know what kind of layer you are added to the map. But the two examples that are here in Leaflet.StyledLayerControl repository, I show how to add layers (without worrying about visibility) and they usually appear. They disappear when they are excluded from the map.
You can specify what kind of layer you are trying to add, and if possible, provide details of the code involved?

**Comment by clluiz** [comment]
In the examples you providade the markers did not came visible too.

My code:

scope.grupos is and array of groups:

 {
                        groupName : name",
                        expanded  : true,
                        layers    : { 
                            "Area 1" : layer
                        }   
                     },

where layer is createad like this: 

        layer = new L.LayerGroup();
        L.geoJson({

            type: 'FeatureCollection',
            features: [

                geometria
            ]

        }).addTo(layer);

Then I add the control:

                    var options = {

                        container_width: "200px",
                        container_maxHeight: "768px",
                        group_maxHeight: "80px"
                    }

                    var control = L.Control.styledLayerControl({}, scope.grupos, options);
Thanks.

**Comment by davicustodio** [comment]
Regarding the example: what you see working http://davicustodio.github.io/Leaflet.StyledLayerControl/examples/example1.html here is equivalent to the code: https://github.com/davicustodio/Leaflet.StyledLayerControl/ blob / master / examples / example1.html

I could not see in your code, vc where this comes the map object. But regardless, a look at the example code and running it!

**Comment by clluiz** [comment]
I have looked, but in the example the markers are not coming visible. But it's possible to control the default visibility of a layer?

**Comment by clluiz** [comment]
I forgot to say that I'm using angular-leaflet-directive and completing the code I give:

                    var options = {

                        container_width: "200px",
                        container_maxHeight: "768px",
                        group_maxHeight: "80px"
                    }

                    var control = L.Control.styledLayerControl({}, scope.grupos, options);
                    map.addControl(control);

**Comment by davicustodio** [comment]
Now I'm understanding. Unfortunately I not tested the use of StyledLayerControl within the angularjs.
As the plugin was created using some JQuery and DOM manual manipulation, I understand that will have problems to work within the angularjs.
Possibly, you would have to readjust it, perhaps defining policies, to work in angularjs.

Perhaps it would be more practical, try to create something using Bootstrap + angularjs, but then u would have to write something from scratch.

**Comment by davicustodio** [comment]
Olá Cleiton, você é brasileiro ?
Se sim, é bom conhecer gente daqui trabalhando com Leaflet e AngularJS. Sou
um entusiasta das tecnologias e frameworks para o desenvolvimento de
Webgis. Quem sabe, poderíamos nos ajudar mutuamente nessa caminhada.

Abraço.

On Thu, May 14, 2015 at 4:33 PM, Cleiton Luiz Rocha Teodoro <
notifications@github.com> wrote:

> I forgot to say that I'm using angular-leaflet-directive and completing
> the code I give:
>
>                 var options = {
>
>                     container_width: "200px",
>                     container_maxHeight: "768px",
>                     group_maxHeight: "80px"
>                 }
>
>                 var control = L.Control.styledLayerControl({}, scope.grupos, options);
>                 map.addControl(control);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davicustodio/Leaflet.StyledLayerControl/issues/6#issuecomment-102145481>
> .
>



-- 
Davi de O. Custódio

**Comment by clluiz** [comment]
Sim, sou brasileiro, não se percebeu pelo péssimo inglês ou se olhou no meu perfil, rsrs. 

Eu também tenho bastante interesse em webgis, não sou um especialista ainda, mas tenho bastante interesse de aprender. Estou usando seu styledlayercontrol porque ele resolve exatamente o problema que estou enferentando para fazer uma app de mapas aqui da empresa.

Nos últimos dias andei estudando a apanhando bastante do leaflet que é uma excelente api. Se eu puder contribuir com alguma coisa seria um prazer.

Abraços.

**Comment by davicustodio** [comment]
@clluiz the commit e0c8133ed90040ceed80d54aeb1e872c6572f990 implement the possibilite to define visible with default to a layer. I dont test in use with AngularJS. Thanks
